In [2]:
import numpy as NP

def horizontal_check(Board):
    for i in range (len(Board)):
        li = []
        for j in range (len(Board)):
            li.append(Board[i][j])
        li_set = set(li)
        x = li_set.pop()
        if len(set(li)) == 0 and x!=0:
            return True
    return False

def vertical_check(Board):
    for i in range (len(Board)):
        li = []
        for j in  range (len(Board)):
            li.append(Board[j][i])
        li_set = set(li)
        x = li_set.pop()
        if len(set(li)) == 0 and x!=0:
            return True
    return False

def diagonal_check(Board):
    diagonal1 = [Board[0,0],Board[1,1],Board[2,2]]
    diagonal2 = [Board[2,0],Board[1,1],Board[0,2]]
    
    diagonal1_set = set(diagonal1)
    diagonal2_set = set(diagonal2)
    x1 = diagonal1_set.pop()
    x2 = diagonal2_set.pop()
    if ( len(diagonal1_set)== 0 and x1!=0) or (len(diagonal2_set) == 0 and x2!=0):
        return True
    else:
         False
            
def check_win(Board):
    return( vertical_check(Board) or horizontal_check(Board) or  diagonal_check(Board) )


def player1_turn(Board):
    try_again = True
    print("Player 1 Turn")
    while try_again == True:
        print("Enter the row or col you want to place")
        li = [ int(i) for i in input().strip().split()]
        if Board[li[0] , li[1]] == 0:
            Board[li[0], li[1]] = 1
            try_again = False
        else:
            print("This palce is slready filled")
    print(Board)
    
def player2_turn(Board):
    try_again = True
    print("Player 2 Turn")
    while try_again == True:
        print("Enter the row or col you want to place")
        li =[int(i) for i in input().strip().split()]
        if Board[li[0], li[1]] == 0:
            Board[li[0], li[1]] = 2
            try_again = False
        else:
            print("This place is already filled")
    print(Board)
    
def play_Game():
    Board = NP.zeros((3,3), dtype = "int32")
    print(Board)
    
    player1_turn(Board)
    player2_turn(Board)
    
    while True:
        player1_turn(Board)
        if check_win(Board) == True:
            print("player1 win")
            break
        player2_turn(Board)
        if check_win(Board) == True:
            print("player2 win")
            break
        

play_Game()

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Player 1 Turn
Enter the row or col you want to place
33


IndexError: list index out of range

In [ ]:
import numpy as NP

def horizontal_check(Board):
    for i in range (len(Board)):
        li = []
        for j in range (len(Board)):
            li.append(Board[i][j])
        li_set = set(li)
        x = li_set.pop()
        if len(set(li)) == 0 and x!=0:
            return True
    return False

def vertical_check(Board):
    for i in range (len(Board)):
        li = []
        for j in  range (len(Board)):
            li.append(Board[j][i])
        li_set = set(li)
        x = li_set.pop()
        if len(set(li)) == 0 and x!=0:
            return True
    return False

def diagonal_check(Board):
    diagonal1 = [Board[0,0],Board[1,1],Board[2,2]]
    diagonal2 = [Board[2,0],Board[1,1],Board[0,2]]
    
    diagonal1_set = set(diagonal1)
    diagonal2_set = set(diagonal2)
    x1 = diagonal1_set.pop()
    x2 = diagonal2_set.pop()
    if ( len(diagonal1_set)== 0 and x1!=0) or (len(diagonal2_set) == 0 and x2!=0):
        return True
    else:
         False
            
def check_win(Board):
    return( vertical_check(Board) or horizontal_check(Board) or  diagonal_check(Board) )


def player1_turn(Board):
    try_again = True
    print("Player 1 Turn")
    while try_again == True:
        print("Enter the row or col you want to place")
        li = [ int(i) for i in input().strip().split()]
        if Board[li[0] , li[1]] == 0:
            Board[li[0], li[1]] = 1
            try_again = False
        else:
            print("This palce is slready filled")
    print(Board)
    
def player2_turn(Board):
    try_again = True
    print("Player 2 Turn")
    while try_again == True:
        print("Enter the row or col you want to place")
        li =[int(i) for i in input().strip().split()]
        if Board[li[0], li[1]] == 0:
            Board[li[0], li[1]] = 2
            try_again = False
        else:
            print("This place is already filled")
    print(Board)
    
def play_Game():
    Board = NP.zeros((3,3), dtype = "int32")
    print(Board)
    
    player1_turn(Board)
    player2_turn(Board)
    
    while True:
        player1_turn(Board)
        if check_win(Board) == True:
            print("player1 win")
            break
        player2_turn(Board)
        if check_win(Board) == True:
            print("player2 win")
            break
        

play_Game()

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Player 1 Turn
Enter the row or col you want to place
0 0
[[1 0 0]
 [0 0 0]
 [0 0 0]]
Player 2 Turn
Enter the row or col you want to place
