In [2]:
import numpy as np


def horizontal_check(board):
    for i in range (len(board)):
        l = []
        for j in range (len(board)):
            l.append(board[i][j])
        l_set = set(l)
        x = l_set.pop()
        if len(set(l)) == 0 and x != 0:
            return True
    return False

def vertical_check(board):
    for j in range (len(board)):
        l = []
        for i in range (len(board)):
            l.append(board[j][i])
        l_set = set(l)
        x = l_set.pop()
        if len(set(l)) == 0 and x != 0:
            return True
    return False

def diagonal_check(board):
    diagonal1 = [board[0,0],board[1,1],board[2,2]]
    diagonal2 = [board[2,0],board[1,1],board[0,2]]
    
    diagonal1_set = set(diagonal1)
    diagonal2_set = set(diagonal2)
    x1 = diagonal1_set.pop()
    x2 = diagonal2_set.pop()
    if(len(diagonal1_set) == 0 and x1!=0) or (len(diagonal2_set) == 0 and x2!=0):
        return True
    else:
        False
        
def check_win(board):
    return( vertical_check(board) or horizontal_check(board) or diagonal_check(board))


def player1_turn(board):
    try_again = True
    print("player 1 Turn")
    while try_again == True:
        print("Enter row or col you want to place your sign")
        l = [int(i) for i in input().strip().split()]
        if board[l[0], l[1]] == 0:
            board[l[0], l[1]] = 1
            try_again = False
        else:
            print("Sorry ! This place is already filled")
    print(board)

def player2_turn(board):
    try_again = True
    print("player 2 Turn")
    while try_again == True:
        print("Enter row or col you want to place your sign")
        l = [int(i) for i in input().strip().split()]
        if board[l[0], l[1]] == 0:
            board[l[0], l[1]] = 2
            try_again = False
        else:
            print("Sorry ! This place is already filled")
    print(board)


def play_game():
    board = np.zeros((3,3), dtype ="int32")
    print(board)
    
    player1_turn(board)
    player2_turn(board)
    
    while True:
        player1_turn(board)
        if check_win(board) == True:
            print("player 1 win")
            break
        player2_turn(board)
        if check_win(board) == True:
            print("player 2 win")
            break
play_game()

[[0 0 0]
 [0 0 0]
 [0 0 0]]
player 1 Turn
Enter row or col you want to place your sign
22


IndexError: list index out of range

In [ ]:
import numpy as np


def horizontal_check(board):
    for i in range (len(board)):
        l = []
        for j in range (len(board)):
            l.append(board[i][j])
        l_set = set(l)
        x = l_set.pop()
        if len(set(l)) == 0 and x != 0:
            return True
    return False

def vertical_check(board):
    for j in range (len(board)):
        l = []
        for i in range (len(board)):
            l.append(board[j][i])
        l_set = set(l)
        x = l_set.pop()
        if len(set(l)) == 0 and x != 0:
            return True
    return False

def diagonal_check(board):
    diagonal1 = [board[0,0],board[1,1],board[2,2]]
    diagonal2 = [board[2,0],board[1,1],board[0,2]]
    
    diagonal1_set = set(diagonal1)
    diagonal2_set = set(diagonal2)
    x1 = diagonal1_set.pop()
    x2 = diagonal2_set.pop()
    if(len(diagonal1_set) == 0 and x1!=0) or (len(diagonal2_set) == 0 and x2!=0):
        return True
    else:
        False
        
def check_win(board):
    return( vertical_check(board) or horizontal_check(board) or diagonal_check(board))


def player1_turn(board):
    try_again = True
    print("player 1 Turn")
    while try_again == True:
        print("Enter row or col you want to place your sign")
        l = [int(i) for i in input().strip().split()]
        if board[l[0], l[1]] == 0:
            board[l[0], l[1]] = 1
            try_again = False
        else:
            print("Sorry ! This place is already filled")
    print(board)

def player2_turn(board):
    try_again = True
    print("player 2 Turn")
    while try_again == True:
        print("Enter row or col you want to place your sign")
        l = [int(i) for i in input().strip().split()]
        if board[l[0], l[1]] == 0:
            board[l[0], l[1]] = 2
            try_again = False
        else:
            print("Sorry ! This place is already filled")
    print(board)


def play_game():
    board = np.zeros((3,3), dtype ="int32")
    print(board)
    
    player1_turn(board)
    player2_turn(board)
    
    while True:
        player1_turn(board)
        if check_win(board) == True:
            print("player 1 win")
            break
        player2_turn(board)
        if check_win(board) == True:
            print("player 2 win")
            break
play_game()

[[0 0 0]
 [0 0 0]
 [0 0 0]]
player 1 Turn
Enter row or col you want to place your sign
0 0
[[1 0 0]
 [0 0 0]
 [0 0 0]]
player 2 Turn
Enter row or col you want to place your sign
1 0
[[1 0 0]
 [2 0 0]
 [0 0 0]]
player 1 Turn
Enter row or col you want to place your sign
0 1
[[1 1 0]
 [2 0 0]
 [0 0 0]]
player 2 Turn
Enter row or col you want to place your sign
2 2
[[1 1 0]
 [2 0 0]
 [0 0 2]]
player 1 Turn
Enter row or col you want to place your sign
0 2
[[1 1 1]
 [2 0 0]
 [0 0 2]]
player 2 Turn
Enter row or col you want to place your sign
